apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      name: example-service-pod
      labels:
        app: example-service
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
        - name: example-service-container
          image: local/simple-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: example-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-no-auth
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /example-service
            pathType: Prefix
            backend:
              service:
                name: example-service
                port:
                  number: 3000
            path: /example-service(/|$)(.*)
